// Parsed keywords from Ads Library Keywordlar.txt
// Keywords are separated by " | " (pipe with spaces)

export const adsLibraryKeywords = [
  'free shipping',
  'worldwide shipping',
  '% off',
  '50% off',
  '60% off',
  '40% off',
  'get yours',
  'buy 1 get 1 free',
  'buy 2 get 2 free',
  'buy 2 get 1 free',
  'get one',
  'introducing the',
  'order today',
  'order yours',
  'limited time',
  'on sale',
  'sale ends',
  'today only',
  'ends soon',
  'bogo',
  'ending soon',
  'shop now',
  'money back',
  'fast shipping',
  'grab yours',
  'grab it',
  'get it',
  'buy it',
  'try it',
  'sold out',
  'click the link',
  'link below',
  'reviews',
  '4.9/5',
  '5/5',
  'trusted by',
  'happy customers',
  'satisfied customers',
  'guarantee',
  '24/7 support',
  'offer ends',
  'dont miss out',
  'say goodbye',
  'order now',
  'save %',
  'usa',
  'no more',
  'reduce',
  'improve',
  'alleviate',
  'enhance',
  'increase',
  'relieve',
  'relief',
  'transform',
  'obsessed',
  'on stock',
  'out of stock',
  '20% off',
  '30% off',
  '10'
]

export const getKeywordsAsString = () => {
  return adsLibraryKeywords.join(' | ')
}

